all:
	@gcc -Wall -Wextra -Werror \
	split.c \
	split_helpers.c \
	mix_helpers.c \
	check_input.c \
	need_name.c \
	expand.c \
	expand2.c \
	expand_helpers.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_numlens.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_substr.c \
	../../lib/libft/src/ft_isprint.c \
	../../lib/libft/src/ft_free_null_term_arrs.c \
	../../lib/libft/src/ft_strtrim.c \
	../../lib/libft/src/ft_strjoin.c \
	../../lib/libft/src/ft_itoa.c \
	../../lib/libft/src/ft_isalnum.c \