all:
	@gcc -Wall -Wextra -Werror \
	tokenize.c \
	tokenize_helpers.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_numlens.c \
	../../lib/libft/src/ft_isspace.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_substr.c \