all:
	@gcc -Wall -Wextra -Werror \
	split.c \
	split_helpers.c \
	split_helpers2.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_numlens.c \
	../../lib/libft/src/ft_isspace.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_substr.c \
	../../lib/libft/src/ft_isprint.c \
	../../lib/libft/src/ft_free_null_term_arrs.c \