all :
	gcc -Wall -Werror -Wextra \
	build_abstract_syntax_tree.c \
	../lexer/tokenize.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_strcmp.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_free_null_term_arrs.c \
	../../lib/libft/src/ft_null_terminated_arr_len.c \
	../../lib/libft/src/ft_substr.c \
