# all :
# 	gcc -Wall -Werror -Wextra \
# 	env_vars.c \
# 	../../lib/libft/src/ft_strdup.c \
# 	../../lib/libft/src/ft_strlen.c \
# 	../../lib/libft/src/ft_strncmp.c \

# init_environ.c
all :
	gcc -Wall -Werror -Wextra \
	env_vars_char.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_strncmp.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_free_null_term_arrs.c \
	../../lib/libft/src/ft_null_terminated_arr_len.c \
	../../lib/libft/src/ft_substr.c \
	../../lib/libft/src/ft_isspace.c \
	../../lib/libft/src/ft_strjoin.c \
	../../lib/libft/src/ft_recalloc.c \
	../../lib/libft/src/ft_memmove.c