# all :
# 	gcc -Wall -Werror -Wextra \
# 	env_vars.c \
# 	../../lib/libft/src/ft_strdup.c \
# 	../../lib/libft/src/ft_strlen.c \
# 	../../lib/libft/src/ft_strncmp.c \

all :
	gcc -Wall -Werror -Wextra \
	join_tokens.c \
	tokenize.c \
	tokenize_helpers.c \
	token_type.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_strcmp.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_isspace.c \
	../../lib/libft/src/ft_isprint.c \
	../../lib/libft/src/ft_free_null_term_arrs.c \
	../../lib/libft/src/ft_null_terminated_arr_len.c \
	../../lib/libft/src/ft_substr.c \
	../../lib/libft/src/ft_numlens.c \
	../../lib/libft/src/ft_isalnum.c \
	../../lib/libft/src/ft_itoa.c \
	../../lib/libft/src/ft_strtrim.c \
	../../lib/libft/src/ft_strjoin.c \
	../parsing/split.c \
	../parsing/split_helpers.c \
	../parsing/split_helpers2.c \
	../parsing/expand.c \
	../parsing/expand_helpers.c \
	../parsing/expand_simple.c \
	../parsing/check_input.c \
