# all :
# 	gcc -Wall -Werror -Wextra \
# 	env_vars.c \
# 	../../lib/libft/src/ft_strdup.c \
# 	../../lib/libft/src/ft_strlen.c \
# 	../../lib/libft/src/ft_strncmp.c \

all :
	gcc -Wall -Werror -Wextra \
	split_multiple_envp.c \
	../env_vars/env_vars.c \
	../../lib/libft/src/ft_strdup.c \
	../../lib/libft/src/ft_strlen.c \
	../../lib/libft/src/ft_strncmp.c \
	../../lib/libft/src/ft_calloc.c \
	../../lib/libft/src/ft_free_null_term_arrs.c \
	../../lib/libft/src/ft_null_terminated_arr_len.c \
	../../lib/libft/src/ft_substr.c \
	../../lib/libft/src/ft_isspace.c \
	../../lib/libft/src/ft_strcmp.c \
	../../lib/libft/src/ft_split.c \
	../../lib/libft/src/ft_strjoin.c \
	../../lib/libft/src/ft_recalloc.c \
	../../lib/libft/src/ft_memmove.c \
	../../lib/libft/src/ft_strtrim.c
